---
- name: debian | updating apt-cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: result
  until: result is successful

- name: debian | installing pre-reqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: true
  register: result
  until: result is successful

# We are removing the old Docker info
- name: debian | Removing Legacy Docker apt-key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: absent
  become: true

# We are removing the old Docker info
- name: debian | Removing Legacy Docker Repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main"
    state: absent
  become: true

- name: debian | adding docker apt-key
  apt_key:
    url: "{{ docker_ubuntu_repo_info['url'] }}"
    id: "{{ docker_ubuntu_repo_info['id'] }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | adding docker repo
  apt_repository:
    repo: "{{ docker_ubuntu_repo_info['repo'] }}"
    state: present
  become: true
  register: result
  until: result is successful

# We remove docker-engine as this is old package to install. The new package is
# docker-ce
- name: debian | uninstalling old docker packages (if exists)
  apt:
    name:
      - containerd
      - docker
      - docker-engine
      - docker.io
      - lxc-docker
      - runc
    state: absent
    purge: true
  become: true
  register: result
  until: result is successful

- name: debian | checking for existing docker # noqa 305
  shell: dpkg-query -W 'docker-ce'
  ignore_errors: true
  register: has_docker
  changed_when: false

- name: debian | installing docker
  apt:
    name:
      - containerd.io
      - "docker-ce={{ docker_version_debian }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: has_docker is failed

- name: debian | Checking For /etc/default/grub
  stat:
    path: /etc/default/grub
  register: _docker_grub_check

- name: debian | setting grub memory limit (if set)
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"'
  register: grub_updated
  become: true
  when:
    - _docker_grub_check['stat']['exists']
    - docker_set_grub_memory_limit is defined
    - docker_set_grub_memory_limit

- name: debian | updating grub (if updated) # noqa 503
  command: update-grub
  become: true
  when: grub_updated['changed']

- name: debian | Installing bridge-utils
  apt:
    name: bridge-utils
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - docker_install_bridge_utils is defined
    - docker_install_bridge_utils
